behaviors:
  default:
    trainer_type: ppo
    hyperparameters:
      batch_size: 32
      buffer_size: 256
      learning_rate: 0.001
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 64
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 500000
    time_horizon: 3
    summary_freq: 20000
    threaded: true
  CarAgent:
    trainer_type: ppo  
    hyperparameters:
      learning_rate_schedule: linear
      learning_rate: 0.0002
      num_epoch: 3
      batch_size: 2048
      buffer_size: 20480
    time_horizon: 1024
    keep_checkpoints: 5
    checkpoint_interval: 500000
    summary_freq: 30000
    max_steps: 15000000
    network_settings:
      vis_encode_type: simple
      normalize: true
      hidden_units: 512
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
    